### ISSUE TITLE
Awesomefonts is not loading

### ISSUE THREAD

**Issue by b4oshany** [collective/collective.fontawesome#8]
The following code in the registry.xml file compiles the font-awesome.min.css file is compiled into plone-compiled.css file:
```
  <records prefix="plone.bundles/fontawesome"
            interface='Products.CMFPlone.interfaces.IBundleRegistry'>
    <value key="enabled">True</value>
    <value key="jscompilation"></value>
    <value key="csscompilation">++resource++collective.fontawesome/css/font-awesome.min.css</value>
    <value key="last_compilation">2019-12-06 00:00:00</value>
    <value key="compile">False</value>
    <value key="depends">plone</value>
  </records>
  ```
Therefore, the relative path to the tff/woff file, which is called in plone-compiled.css file is broken. In otherwords, the following code result in the screenshot below:
```css
@font-face {
  font-family: 'Font Awesome 5 Brands';
  font-style: normal;
  font-weight: normal;
  src: url("../webfonts/fa-brands-400.eot");
  src: url("../webfonts/fa-brands-400.eot?#iefix") format("embedded-opentype"), url("../webfonts/fa-brands-400.woff2");
}
```
![image](https://user-images.githubusercontent.com/1830494/50315589-60a18080-0481-11e9-8a94-008d4a59e2fe.png)

***++plone++static/webfonts/fa-brands-400.woff2 url does not exists***
